version: '3'
services:
  go:
    hostname: golang1-15
    build:
      context: ./docker/server
    container_name: server-go
    ports:
      - 8081:8081
    volumes:
      - ./app/server:/go/src/server
    working_dir: /go/src/server
    tty: true
    # command: >
    #   sh -c "
    #     go mod download
    #     realize start --run
    #   "

  nginx:
    hostname: nginx
    image: nginx
    depends_on:
      - go
    container_name: nginx
    ports:
      - 80:80
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
